### ISSUE TITLE
Can you add info as to how to download and develop this as local copy?

### ISSUE THREAD

**Issue by mavavilj** [Michael-F-Bryan/arcs#32]
Can you add info as to how to download and develop this as local copy?

(Sorry I'm Rust newbie)

So explain what to download, where to place it, what to call (cargo build etc.), how to import.

**Comment by Michael-F-Bryan** [comment]
I probably won't add it to the README because the instructions are the same as pretty much every Rust project, but if you want to start developing this locally you would do the following:

```console
$ git clone https://github.com/Michael-F-Bryan/arcs/ && cd arcs
$ cargo build
```

If you want to see an example of how the code might be used, check out [`render_to_image.rs`](https://github.com/Michael-F-Bryan/arcs/blob/master/arcs/examples/render_to_image.rs) in the `arcs/examples/` folder.

That said, development was [moved to GitLab](https://gitlab.com/Michael-F-Bryan/arcs) some time ago, so you might find that repo more interesting.
